### ISSUE TITLE
Credits Seite

### ISSUE THREAD

**Issue by ReimarBauer** [pysv/pysv.org#103]
Konkreter Anlass ist  Realobjects wünscht sich Verlinkung auf der PySV Seite, 
Email Anfrage von Andreas Jung:

Könnnen wir den "Credits" Text von
https://ep2014.europython.eu/en/conference/legal-notice/
auch auf die PySV Seite übernehmen (Impressum oder sonst wo)?

Im Emailverlauf sind wir überein gekommen, das es evtl. besser ist eine allgemeinere "Credits Seite" zu erstellen, diese könnte z.B. im Theme oberhalb von Impressum eingeordnet werden. 

Da wir noch andere Produkte wie z.B. Jira weiter einsetzen möchten, ist eine allgemeinere Seite mit diesen Informationen sinnvoll. 

Für das Produkt sollten wir intern eine Beschreibungseite Seite haben, mit Kontakt und Lizenznutzungs information.

**Comment by obestwalter** [comment]
done - erstmal ohne Logo
