### ISSUE TITLE
teaser unconference mit teaser pythoncamp austauschen

### ISSUE THREAD

**Issue by ReimarBauer** [pysv/pysv.org#113]
Das PythonCamp in Köln http://pythoncamp.de findet vom 28.3 bis 29.3 in den Räumen der GFU Cyrus AG statt

**Comment by acsr** [comment]
Deaktiviert und Prozedur im PySV FAQ dokumentiert.

**Comment by acsr** [comment]
Neue Jira tickets angelegt: 

Prozedur für Austausch Banner auf Startseite dokumentieren
https://jira.pysv.org/browse/VWEB-3, 

Teaser Banner für PythonCamp in Köln erstellen
https://jira.pysv.org/browse/PRES-2
