### ISSUE TITLE
SSL-Zertifikate

### ISSUE THREAD

**Issue by Marrin** [pysv/pysv.org#123]
Ich weiss nicht ob ich damit hier richtig bin‽  Falls nicht, schubst mich mal bitte jemand in die richtige Richtung. Danke.

Beim Python-Wiki ist das Zertifikat neulich ausgelaufen:

> wiki.pythonde.pysv.org uses an invalid security certificate. The certificate expired on 3 May 2017 at 15:54. The current time is 6 July 2017 at 14:02.

Und bei pysv.org sieht es noch schlimmer aus = länger her und falscher Domainname:

> pysv.org uses an invalid security certificate. The certificate is only valid for the following names: www.dzug.org, dzug.org The certificate expired on 29 September 2015 at 17:35. The current time is 6 July 2017 at 14:14.

**Comment by obestwalter** [comment]
Hi @Marrin das repo hier hat sich leider nicht durchgesetzt. Das ist alles in einem internen Jira. Schreib am Besten an info@python-verband.org um rauszufinden, wer das was grad macht.

**Comment by obestwalter** [comment]
Hallo @Marrin, dieses repo ist leider nicht mehr aktuell. Der Verband regelt seine Angelegenheiten seit einiger Zeit in einem privaten Jira Board. Die Probleme sind aber bereits bekannt. Es fehlt einfach an Freiwilligen, die Zeit und Energie haben, sich dieser Probleme anzunehmen. Wenn Du helfen willst, wende Dich am Besten per email direkt an den Vorstand.
