### ISSUE TITLE
Migration und Update der Dienstleister

### ISSUE THREAD

**Issue by jensens** [pysv/pysv.org#5]
Die Dienstleister der http://www.zope.de/support/zope-dienstleister/anbieter_alle müssen geprueft, migriert und ergaenzt und aufgehuebscht werden.

**Comment by obestwalter** [comment]
Wird durch competencedir abgelöst. Mitglieder werden angeschrieben und können sich dann eintragen

**Comment by obestwalter** [comment]
sieh #104
