### ISSUE TITLE
Klar kommunizieren über welche  Kanäle der PySV seine Mitteilungen ankündigt!

### ISSUE THREAD

**Issue by obestwalter** [pysv/pysv.org#65]
... über Mailingliste

**Comment by obestwalter** [comment]
diskussion@lists.python-verband.org
twitter: 

hier sammeln, wo man das rauspusten soll.

**Comment by acsr** [comment]
Die Kommunikationskanäle werder derzeit auf der Seite http://python-verband.org/der-verband/kommunikation gesammelt.

- Bitte ergänzen und ggf. aufgabenorientiert erwähnen

**Comment by obestwalter** [comment]
siehe #93
