### ISSUE TITLE
styling von Mitglied werden verbessern

### ISSUE THREAD

**Issue by ReimarBauer** [pysv/pysv.org#74]
![bildschirmfoto vom 2014-06-22 10 02 53](https://cloud.githubusercontent.com/assets/278728/3350918/b291fef4-f9e3-11e3-8bed-e2fbab624cca.png)

in meiner Ansicht geht der untere Balken durch den Text

**Comment by obestwalter** [comment]
wir verwenden hoffentlich bald ws anderes
