### ISSUE TITLE
Adresse/Logo im Mitgliedsantrag fixen

### ISSUE THREAD

**Issue by ReimarBauer** [pysv/pysv.org#75]
Im Mitgliedsantrag steht noch immer der Sitz als Anschrift, sollte auf Geschäftsanschrift geändert werden

http://python-verband.org/mitmachen/mitglied/antrag-auf-mitgliedschaft-im-pysv.pdf

Das Logo sollte das des Vereins sein, nicht das generische Python Logo.

Auf den Antrag muss unbedingt noch zum Abwählen, das nicht zugestimmt wird zu Mitgliedsversammlungen per Mail eingeladen zu werden (Default is Zustimmung)

**Comment by obestwalter** [comment]
Anschrift passt, Logo muss noch geändert.

**Comment by acsr** [comment]
Logo geändert und hochgeladen. Quellen ist kritisch. Ich habe hier bei mir noch Masterdateien aus Libre Office von JUH liegen. Die letzten Fixes habe ich allerdings direkt in Acrobat gemacht und jetzt auch dort einfach das Logo getauscht. 

Aus meiner Sicht würde ich das bei der nächsten Änderung komplett neu bauen. Die Vorlage war total verbastelt. Ansonsten bitte bei mir anfragen. Sourcen Aufbereiten ist m.E. mehr Arbeit als neu bauen. 

Mache das jetzt zu.

**Comment by acsr** [comment]
Nachtrag: Scribus Sourcen sind jetzt ins Jira Ticket https://jira.pysv.org/browse/VWEB-40 "Mitgliedantrag aktualisieren" hochgeladen!
