### ISSUE TITLE
Referate / Referenten

### ISSUE THREAD

**Issue by ReimarBauer** [pysv/pysv.org#78]
Die Referate sollten in der Navigation auftauchen, mit jeweiliger Kurzbeschreibung .
Dann mit den AGs vernetzen.

**Comment by obestwalter** [comment]
Wer ist das geanu?

Die müssen dann eingetragen werden auf der Webseite.

**Comment by obestwalter** [comment]
Datenschutzbeauftrager? Siehe: https://github.com/pysv/pysv.org/issues/86

**Comment by acsr** [comment]
Portlets Pressesprecher und Öffentlichkeitsarbeit  links auf und unterhalb von http://python-verband.org/informieren/ und Texte unter http://python-verband.org/der-verband/kommunikation/ansprechpartner ergänzt.

Es fehlt ein Ansprechpartner für die Infastruktur!

**Comment by acsr** [comment]
verschiebe Ticket jetzt ins Jira. Wird geschlossen wenn erledigt.

**Comment by acsr** [comment]
moved to https://jira.pysv.org/browse/VWEB-16
