### ISSUE TITLE
Twitterwall unter News anzeigen?

### ISSUE THREAD

**Issue by ReimarBauer** [pysv/pysv.org#79]
Können wir unter news auch Twitter messages anzeigen, so wie hier https://www.python.org/community/workshops/ ?

http://python-verband.org/informieren/news

**Comment by obestwalter** [comment]
pythonbezogens zeug anzeigen

**Comment by obestwalter** [comment]
https://waffle.io/pysv/pysv.org/cards/54f4b08b2a8c950f0079f072
