### ISSUE TITLE
Server Konfiguration klären.

### ISSUE THREAD

**Issue by obestwalter** [pysv/pysv.org#90]
wie ist nginx konfiguriert?

Warum haben wir zwei Instanzen, aber keinen Load Balancer.

Anyone? @ctheune

**Comment by acsr** [comment]
Projekt Infrastruktur klemmt derzeit immer noch. Wenn ich Zeit habe funzt im Jira nichts. Und wenn es dann endlich funzt. Habe ich keine Zeit mehr. Siehe auch Jira Ticket/Projekt: https://jira.pysv.org/projects/INF .

@jensens kann das jetzt ins Jira? Ist ja ein Metathema oberhalb des Plone Buildouts.

**Comment by obestwalter** [comment]
Ins Jira importiert
