### ISSUE TITLE
Übersichtsseite noch nicht veröffentlichter Inhalte die ich veröffentlichen darf

### ISSUE THREAD

**Issue by ReimarBauer** [pysv/pysv.org#99]
Es wäre gut es gäbe für mich einen einfachen Weg zu sehen, welche Inhalte noch Veröffentlicht werden müssen.  Wie erhalte ich eine Übersicht?

**Comment by jensens** [comment]
Plone Trivia: Collection machen und auf private Filtern. Das ist ein Doku-Task.
